[package]
version = "0.0.1"
name = "fs"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
bazel_protos = { path = "../process_execution/bazel_protos" }
boxfuture = { path = "../boxfuture" }
byteorder = "1"
bytes = "0.4.5"
digest = "0.8"
dirs = "1"
futures = "^0.1.16"
futures-cpupool = "0.1"
glob = "0.2.11"
grpcio = { git = "https://github.com/pantsbuild/grpc-rs.git", rev = "4dfafe9355dc996d7d0702e7386a6fedcd9734c0", default_features = false, features = ["protobuf-codec"] }
hashing = { path = "../hashing" }
ignore = "0.4.4"
indexmap = "1.0.2"
itertools = "0.7.2"
lazy_static = "1"
lmdb = { git = "https://github.com/pantsbuild/lmdb-rs.git", rev = "06bdfbfc6348f6804127176e561843f214fc17f8" }
log = "0.4"
parking_lot = "0.6"
protobuf = { version = "2.0.4", features = ["with-bytes"] }
sha2 = "0.8"
serde = "1.0"
serde_derive = "1.0"
tempfile = "3"
uuid = { version = "0.7.1", features = ["v4"] }

[dev-dependencies]
mock = { path = "../testutil/mock" }
testutil = { path = "../testutil" }
walkdir = "2"
