[package]
version = "0.0.1"
name = "fs"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
bazel_protos = { path = "../process_execution/bazel_protos" }
boxfuture = { path = "../boxfuture" }
byteorder = "1"
bytes = "0.4.5"
digest = "0.7"
dirs = "1"
futures = "^0.1.16"
futures-cpupool = "0.1"
glob = "0.2.11"
grpcio = { git = "https://github.com/pantsbuild/grpc-rs.git", rev = "4dfafe9355dc996d7d0702e7386a6fedcd9734c0", features = ["secure"] }
hashing = { path = "../hashing" }
ignore = "0.3.1"
indexmap = "1"
itertools = "0.7.2"
lazy_static = "1"
lmdb = "0.8"
log = "0.4"
parking_lot = "0.6"
protobuf = { version = "2.0.4", features = ["with-bytes"] }
resettable = { path = "../resettable" }
sha2 = "0.7"
serde = "1.0"
serde_derive = "1.0"
uuid = { version = "0.7.1", features = ["v4"] }

[dev-dependencies]
mock = { path = "../testutil/mock" }
tempfile = "3"
testutil = { path = "../testutil" }
