[package]
version = "0.0.1"
edition = "2018"
name = "fs"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
async-trait = "0.1"
bytes = "0.4.5"
futures = "0.3"
glob = "0.2.11"
ignore = "0.4.11"
lazy_static = "1"
log = "0.4"
parking_lot = "0.11"
rlimit = "0.3"
task_executor = { path = "../task_executor" }

[dev-dependencies]
tempfile = "3"
testutil = { path = "../testutil" }
# TODO: See #10291.
tokio = { version = "=0.2.20", features = ["rt-core", "macros"] }
