[package]
version = "0.0.1"
name = "fs"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[dependencies]
bazel_protos = { path = "../process_execution/bazel_protos" }
boxfuture = { path = "../boxfuture" }
digest = "0.6.2"
futures = "0.1.16"
futures-cpupool = "0.1.6"
glob = "0.2.11"
grpcio = { version = "0.2.0", features = ["secure"] }
hex = "0.3.1"
ignore = "0.3.1"
itertools = "0.7.2"
lazy_static = "0.2.2"
lmdb = "0.7.2"
ordermap = "0.2.8"
protobuf = "1.4.1"
sha2 = "0.6.0"
tar = "0.4.13"
tempdir = "0.3.5"

[dev-dependencies]
testutil = { path = "../testutil" }
