[package]
version = "0.0.1"
name = "fs"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[dependencies]
bazel_protos = { path = "../process_execution/bazel_protos" }
boxfuture = { path = "../boxfuture" }
byteorder = "1"
bytes = "0.4.5"
digest = "0.6.2"
futures = "0.1.16"
futures-cpupool = "0.1.6"
glob = "0.2.11"
grpcio = { version = "0.2.0", features = ["secure"] }
hashing = { path = "../hashing" }
hex = "0.3.1"
ignore = "0.3.1"
indexmap = "1"
itertools = "0.7.2"
lazy_static = "0.2.2"
lmdb = "0.7.2"
log = "0.4"
protobuf = { version = "1.4.1", features = ["with-bytes"] }
sha2 = "0.6.0"
tempdir = "0.3.5"

[dev-dependencies]
mock = { path = "../testutil/mock" }
testutil = { path = "../testutil" }
