[package]
version = "0.0.1"
edition = "2018"
name = "grpc_util"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
bytes = "1.0"
either = "1"
futures = "0.3"
hyper = "0.14"
http = "0.2"
itertools = "0.10"
rustls-native-certs = "0.5"
prost = "0.8"
rand = "0.8"
rustls = { version = "0.19", features = ["dangerous_configuration"] }
rustls-pemfile = "0.2"
tokio = { version = "1.4", features = ["net", "process", "rt-multi-thread", "sync", "time"] }
tokio-rustls = "0.22"
tokio-util = { version = "0.6", features = ["codec"] }
tonic = { version = "0.5", features = ["transport", "codegen", "tls", "tls-roots", "prost"] }
tower = { version = "0.4", features = ["limit", "retry"] }
tower-layer = "0.3"
tower-service = "0.3"
webpki = "0.21"

[dev-dependencies]
async-trait = "0.1"
parking_lot = "0.11"
prost-types = "0.8"

[build-dependencies]
prost-build = "0.8"
tonic-build = "0.5.1"
