[package]
version = "0.0.1"
edition = "2024"
name = "options_pants_ng"
authors = ["Pants Build <pantsbuild@gmail.com>"]
publish = false

[dependencies]
glob = { workspace = true }
options = { path = "../../options" }
regex = { workspace = true }
shlex = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
