[build-system]
# Using the oldest `setuptools` that allows `package_dists_integration_test.py` to pass on Python 3.14
requires = ["setuptools==66.1.0", "wheel==0.37.0", "ansicolors==1.1.8"]
build-backend = "setuptools.build_meta"
