[package]
name = "ui"
version = "0.0.1"
edition = "2021"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[lib]
path = "src/console_ui.rs"

[dependencies]
console = "0.15.0"
futures = "0.3"
indexmap = "1.8"
indicatif = "0.16.2"
logging = { path = "../logging" }
parking_lot = "0.11"
stdio = { path = "../stdio" }
terminal_size = "0.1.15"
task_executor = { path = "../task_executor" }
uuid = { version = "0.8", features = ["v4"] }
workunit_store = { path = "../workunit_store" }
