[package]
name = "ui"
version = "0.0.1"
edition = "2018"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[lib]
path = "src/console_ui.rs"

[dependencies]
futures = { version = "0.3" }
indicatif = "0.14.0"
indexmap = "1.4"
uuid = { version = "0.7", features = ["v4"] }
logging = { path = "../logging" }
task_executor = { path = "../task_executor" }
workunit_store = { path = "../workunit_store" }
