[package]
version = "0.0.1"
edition = "2018"
name = "logging"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
colored = "1.9.0"
chrono = "0.4.10"
lazy_static = "1"
log = "0.4"
num_enum = "0.4"
parking_lot = "0.11"
tokio = { version = "=0.2.22", features = ["rt-util"] } # TODO: see https://github.com/pantsbuild/pants/issues/10291
uuid = { version = "0.7", features = ["v4"] }

[build-dependencies]
cargo_metadata = "0.10"
