[package]
version = "0.0.1"
edition = "2018"
name = "logging"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
lazy_static = "1"
log = "0.4"
num_enum = "0.1.1"
parking_lot = "0.6"
simplelog = "0.5.3"
ui = { path = "../ui" }
