[package]
name = "mock"
version = "0.0.1"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
bazel_protos = { path = "../../process_execution/bazel_protos" }
bytes = "0.4.5"
futures = "^0.1.16"
grpcio = { git = "https://github.com/pantsbuild/grpc-rs.git", rev = "bfd7333281c0422028502ccc7f78c57c27fdec08", features = ["secure"] }
hashing = { path = "../../hashing" }
protobuf = { version = "2.0.4", features = ["with-bytes"] }
testutil = { path = ".." }
