[package]
name = "mock"
version = "0.0.1"
edition = "2018"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
async-stream = "0.2"
bazel_protos = { path = "../../process_execution/bazel_protos" }
bytes = "0.5"
futures01 = { package = "futures", version = "0.1" }
futures = { version = "0.3", features = ["compat"] }
hashing = { path = "../../hashing" }
hyper = { version = "0.13", features = ["stream", "tcp"] }
log = "0.4"
parking_lot = "0.11"
prost = { git = "https://github.com/danburkert/prost", rev = "a1cccbcee343e2c444e1cd2738c7fba2599fc391" }
prost-types = "0.6"
testutil = { path = ".." }
tokio = { version = "0.2.23", features = ["time"] }
tonic = { version = "0.3" }
