[package]
name = "mock"
version = "0.0.1"
edition = "2021"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
async-stream = "0.3"
protos = { path = "../../protos" }
bytes = "1.0"
futures = "0.3"
grpc_util = { path = "../../grpc_util" }
hashing = { path = "../../hashing" }
hyper = { version = "0.14", features = ["stream", "tcp"] }
log = "0.4"
parking_lot = "0.12"
prost = "0.10"
prost-types = "0.9"
testutil = { path = ".." }
tokio = { version = "1.16", features = ["time"] }
tonic = { version = "0.6" }
