[package]
name = "mock"
version = "0.0.1"
edition = "2021"
authors = ["Pants Build <pantsbuild@gmail.com>"]
publish = false

[dependencies]
async-stream = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
grpc_util = { path = "../../grpc_util" }
hashing = { path = "../../hashing" }
hyper = { workspace = true, features = ["stream", "tcp"] }
log = { workspace = true }
parking_lot = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
protos = { path = "../../protos" }
testutil = { path = ".." }
tokio = { workspace = true, features = ["time"] }
tonic = { workspace = true }
