# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      gha-deps:
        patterns:
          - "*"
    ignore:
      - dependency-name: "dawidd6/action-send-mail"
      - dependency-name: "mheap/github-action-required-labels"
    labels:
      - "category:internal"
      - "dependencies"
      - "release-notes:not-required"
    reviewers:
      - sureshjoshi
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directory: "/src/rust"
    ignore:
      # No longer developed, referred to 1.3.3 as complete, lots of drama (https://sr.ht/~stygianentity/bincode/ and https://old.reddit.com/r/rust/comments/1pnz1iz/bincode_development_has_ceased_permanently/)
      - dependency-name: "bincode" 
    groups:
      rust-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      rust-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
    labels:
      - "category:internal"
      - "dependencies"
      - "release-notes:not-required"
    reviewers:
      - benjyw
      - cburroughs
      - sureshjoshi
      - tdyas
    schedule:
      interval: "monthly"
  
  - package-ecosystem: pip
    directory: "/3rdparty/python"
    groups:
      python-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      python-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
    labels:
      - "category:internal"
      - "dependencies"
      - "release-notes:not-required"
    reviewers:
      - benjyw
      - cburroughs
      - sureshjoshi
      - tdyas
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directories: 
      - "build-support/**/*"
      - "src/python/pants/backend/javascript/**/*"
      - "src/python/pants/backend/typescript/**/*"
      - "testprojects/src/js/**/*"
      - "testprojects/src/ts/**/*"
    groups:
      js-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      js-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
    labels:
      - "category:internal"
      - "dependencies"
      - "release-notes:not-required"
    reviewers:
      - sureshjoshi
    schedule:
      interval: "monthly"
