[GLOBAL]
# Override color support detection - we want colors and Travis supports them.
colors = true
# TODO: See #9924.
dynamic_ui = false

# TODO: Eventually we would like pantsd enabled in CI as well, but we blanket disable it for
# now in order to smooth off rough edges locally.
pantsd = false

[test]
use_coverage = true

[pytest]
junit_xml_dir = "dist/test-results/"

[coverage-py]
report = ["raw", "xml"]

#[auth]
#from_env_var = "TOOLCHAIN_AUTH_TOKEN"
#org = "pantsbuild"
#ci_env_variables = ["TRAVIS", "TRAVIS_JOB_ID", "TRAVIS_BUILD_ID", "TRAVIS_PULL_REQUEST", "TRAVIS_BUILD_WEB_URL"]
#
#[buildsense]
#enable = true
