[package]
name = "sharded_lmdb"
version = "0.0.1"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
edition = "2021"

[dependencies]
bytes = "1.2"
fs = { path = "../fs" }
futures = "0.3"
hashing = { path = "../hashing" }
lmdb-rkv = { git = "https://github.com/pantsbuild/lmdb-rs.git", rev = "6ae7a552aa2c932c3ddf652a68cdde2fed547cbc" }
log = "0.4"
task_executor = { path = "../task_executor" }
tempfile = "3.5.0"

[dev-dependencies]
parking_lot = "0.12"
tokio = { version = "1.21", features = ["macros"] }
