[package]
version = "0.0.1"
edition = "2024"
name = "docker"
authors = ["Pants Build <pantsbuild@gmail.com>"]
publish = false

[dependencies]
async-stream = { workspace = true }
async-trait = { workspace = true }
bollard = { workspace = true }
docker_credential = { workspace = true }
fs = { path = "../../fs" }
futures = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
maplit = { workspace = true }
nails = { workspace = true }
store = { path = "../../fs/store" }
task_executor = { path = "../../task_executor" }
tokio = { workspace = true, features = ["net", "process", "rt-multi-thread", "sync", "time"] }
workunit_store = { path = "../../workunit_store" }
parking_lot = { workspace = true }
async-oncecell = { workspace = true }
once_cell = { workspace = true }
process_execution = { path = ".." }
hashing = { path = "../../hashing" }
bytes = { workspace = true }
shell-quote = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
mock = { path = "../../testutil/mock" }
parameterized = { workspace = true }
parking_lot = { workspace = true }
sharded_lmdb = { path = "../../sharded_lmdb" }
tempfile = { workspace = true }
testutil = { path = "../../testutil" }
tokio = { workspace = true, features = ["macros"] }

[lints]
workspace = true
