[package]
name = "serverset"
version = "0.0.1"
edition = "2018"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
boxfuture = { path = "../boxfuture" }
futures = "^0.1.16"
parking_lot = "0.6"
tokio-timer = "0.2"

[dev-dependencies]
tokio = "0.1"
