[package]
name = "serverset"
version = "0.0.1"
edition = "2018"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
boxfuture = { path = "../boxfuture" }
futures01 = { package = "futures", version = "0.1" }
futures = { version = "0.3", features = ["compat"] }
parking_lot = "0.6"
tokio = { version = "0.2", features = ["time"] }

[dev-dependencies]
maplit = "1"
testutil = { path = "../testutil" }
tokio = { version = "0.2", features = ["rt-core"] }
