[package]
version = "0.0.1"
edition = "2021"
name = "rule_graph"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
# TODO: Waiting on https://github.com/Aeledfyr/deepsize/pull/{30,31,32}.
deepsize = { git = "https://github.com/stuhood/deepsize.git", rev = "5c8bee5443fcafe4aaa9274490d354412d0955c1", features=["internment", "smallvec"] }
indexmap = "1.9"
internment = "0.6"
log = "0.4"
petgraph = "0.6"
smallvec = "1"

[dev-dependencies]
env_logger = "0.9.0"
