[package]
version = "0.0.1"
edition = "2021"
name = "nailgun"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
async_latch = { path = "../async_latch" }
bytes = "1.2"
futures = "0.3"
log = "0.4"
nails = "0.13"
os_pipe = "1.0"
task_executor = { path = "../task_executor" }
tokio = { version = "1.16", features = ["fs", "io-std", "io-util", "net", "signal", "sync"] }

[dev-dependencies]
tokio = { version = "1.16", features = ["io-std", "macros", "net", "rt-multi-thread"] }
