[package]
version = "0.0.1"
edition = "2018"
name = "async_semaphore"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
parking_lot = "0.11"

[dev-dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["rt-core", "macros", "time"] }
