[package]
version = "0.0.1"
edition = "2018"
name = "async_semaphore"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
futures = "^0.1.16"
log = "0.4"
parking_lot = "0.6"


[dev-dependencies]
tokio-timer = "0.2"
tokio-compat = { version = "0.1", features = ["rt-full"] }
