[package]
name = "brfs"
version = "0.0.1"
edition = "2018"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
bazel_protos = { path = "../../process_execution/bazel_protos" }
clap = "2"
dirs = "1"
env_logger = "0.5.4"
errno = "0.2.3"
fuse = "0.3.1"
futures01 = { package = "futures", version = "0.1" }
futures = { version = "0.3", features = ["compat"] }
hashing = { path = "../../hashing" }
libc = "0.2.39"
log = "0.4.1"
parking_lot = "0.6"
protobuf = { version = "2.0.6", features = ["with-bytes"] }
serverset = { path = "../../serverset" }
store = { path = "../store" }
task_executor = { path = "../../task_executor" }
time = "0.1.39"
tokio = { git = "https://github.com/tokio-rs/tokio", rev = "a5c87981077a784b2adebe7cf27267cef6ec9fac", features = ["rt-threaded", "macros"] }
workunit_store = { path = "../../workunit_store" }

[dev-dependencies]
bytes = "0.4.5"
tempfile = "3"
testutil = { path = "../../testutil" }
