[package]
name = "brfs"
version = "0.0.1"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
bazel_protos = { path = "../../process_execution/bazel_protos" }
clap = "2"
env_logger = "0.5.4"
errno = "0.2.3"
fs = { path = ".." }
fuse = "0.3.1"
futures = "^0.1.16"
hashing = { path = "../../hashing" }
libc = "0.2.39"
log = "0.4.1"
protobuf = { version = "2.0.4", features = ["with-bytes"] }
time = "0.1.39"

[dev-dependencies]
bytes = "0.4.5"
tempfile = "3"
testutil = { path = "../../testutil" }
