[package]
name = "brfs"
version = "0.0.1"
edition = "2018"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
bazel_protos = { path = "../../process_execution/bazel_protos" }
clap = "2"
dirs-next = "2"
env_logger = "0.5.4"
errno = "0.2.3"
fuse = "0.3.1"
futures = "0.3"
hashing = { path = "../../hashing" }
libc = "0.2.39"
log = "0.4.1"
parking_lot = "0.11"
protobuf = { version = "2.0.6", features = ["with-bytes"] }
store = { path = "../store" }
task_executor = { path = "../../task_executor" }
time = "0.1.39"
tokio = { version = "1.4", features = ["rt-multi-thread", "macros", "signal"] }
tokio-stream = { version = "0.1", features = ["signal"] }
workunit_store = { path = "../../workunit_store" }

[dev-dependencies]
bytes = "1.0"
tempfile = "3"
testutil = { path = "../../testutil" }
