[package]
version = "0.0.1"
name = "process_execution"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
async_semaphore = { path = "../async_semaphore" }
bazel_protos = { path = "bazel_protos" }
boxfuture = { path = "../boxfuture" }
bytes = "0.4.5"
digest = "0.6.2"
fs = { path = "../fs" }
futures = "^0.1.16"
grpcio = { version = "0.3", features = ["secure"] }
hashing = { path = "../hashing" }
log = "0.4"
protobuf = { version = "2.0.4", features = ["with-bytes"] }
resettable = { path = "../resettable" }
sha2 = "0.6.0"
tempfile = "3"
futures-timer = "0.1"
tokio-codec = "0.1"
tokio-process = "0.2.1"

[dev-dependencies]
mock = { path = "../testutil/mock" }
tempfile = "3"
testutil = { path = "../testutil" }
