[package]
version = "0.0.1"
edition = "2018"
name = "process_execution"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
copy_dir = "0.1.2"
walkdir = "2"
async_semaphore = { path = "../async_semaphore" }
bazel_protos = { path = "bazel_protos" }
boxfuture = { path = "../boxfuture" }
bytes = "0.4.5"
derivative = "1.0.2"
digest = "0.8"
fs = { path = "../fs" }
futures = "^0.1.16"
grpcio = { git = "https://github.com/pantsbuild/grpc-rs.git", rev = "b582ef3dc4e8c7289093c8febff8dadf0997b532", default_features = false, features = ["protobuf-codec", "secure"] }
hashing = { path = "../hashing" }
libc = "0.2.39"
log = "0.4"
parking_lot = "0.6"
protobuf = { version = "2.0.6", features = ["with-bytes"] }
serde = "1"
serde_json = "1"
sha2 = "0.8"
sharded_lmdb = {  path = "../sharded_lmdb" }
store = { path = "../fs/store" }
task_executor = { path = "../task_executor" }
tempfile = "3"
concrete_time = { path = "../concrete_time" }
tokio = "0.1"
tokio-codec = "0.1"
tokio-process = "0.2.1"
tokio-timer = "0.2"
uname = "0.1.1"
workunit_store = { path = "../workunit_store" }

[dev-dependencies]
maplit = "1.0.1"
mock = { path = "../testutil/mock" }
parking_lot = "0.6"
spectral = "0.6.0"
tempfile = "3"
testutil = { path = "../testutil" }
