[package]
version = "0.0.1"
name = "process_execution"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[dependencies]
bazel_protos = { path = "bazel_protos" }
boxfuture = { path = "../boxfuture" }
bytes = "0.4.5"
digest = "0.6.2"
fs = { path = "../fs" }
futures = "0.1.21"
grpcio = { version = "0.2.0", features = ["secure"] }
hashing = { path = "../hashing" }
log = "0.4"
protobuf = { version = "1.4.1", features = ["with-bytes"] }
sha2 = "0.6.0"
tempdir = "0.3.5"
tokio-timer = "0.2.1"

[dev-dependencies]
mock = { path = "../testutil/mock" }
tempdir = "0.3.5"
testutil = { path = "../testutil" }
