[package]
version = "0.0.1"
edition = "2018"
name = "process_execution"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
async-trait = "0.1"
walkdir = "2"
async_semaphore = { path = "../async_semaphore" }
bazel_protos = { path = "bazel_protos" }
bytes = "0.5"
derivative = "2.1.1"
grpc_util = { path = "../grpc_util" }
fs = { path = "../fs" }
futures = { version = "0.3", features = ["compat"] }
hashing = { path = "../hashing" }
libc = "0.2.39"
log = "0.4"
nails = "0.8"
sha2 = "0.9"
sharded_lmdb = {  path = "../sharded_lmdb" }
shell-quote = "0.1.0"
store = { path = "../fs/store" }
task_executor = { path = "../task_executor" }
tempfile = "3"
concrete_time = { path = "../concrete_time" }
tokio = { version = "0.2.23", features = ["process", "rt-threaded", "sync", "tcp", "time"] }
tokio-rustls = "0.14"
tokio-util = { version = "0.2", features = ["codec"] }
uname = "0.1.1"
uuid = { version = "0.7", features = ["v4"] }
workunit_store = { path = "../workunit_store" }
regex = "1"
lazy_static = "1"
parking_lot = "0.11"
itertools = "0.8.0"
serde = "1.0.104"
bincode = "1.2.1"
double-checked-cell-async = "2.0"
rand = "0.6"
prost = { git = "https://github.com/danburkert/prost", rev = "a1cccbcee343e2c444e1cd2738c7fba2599fc391" }
prost-types = "0.6"
tonic = { version = "0.3", features = ["transport", "codegen", "tls", "tls-roots", "prost"] }
tryfuture = { path = "../tryfuture" }

[dev-dependencies]
maplit = "1.0.1"
mock = { path = "../testutil/mock" }
parking_lot = "0.11"
spectral = "0.6.0"
tempfile = "3"
testutil = { path = "../testutil" }
tokio = { version = "0.2.23", features = ["macros"] }
