[package]
version = "0.0.1"
edition = "2018"
name = "process_execution"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
async-trait = "0.1"
copy_dir = "0.1.2"
walkdir = "2"
async_semaphore = { path = "../async_semaphore" }
bazel_protos = { path = "bazel_protos" }
boxfuture = { path = "../boxfuture" }
bytes = "0.4.5"
derivative = "2.1.1"
digest = "0.8"
fs = { path = "../fs" }
futures01 = { package = "futures", version = "0.1" }
futures = { version = "0.3", features = ["compat"] }
# TODO: This is 0.5.1 + https://github.com/tikv/grpc-rs/pull/457 + a workaround for https://github.com/rust-lang/cargo/issues/8258
grpcio = { git = "https://github.com/pantsbuild/grpc-rs.git", rev = "ed3afa3c24ddf1fdd86826e836f57c00757dfc00", default_features = false, features = ["protobuf-codec", "secure"] }
hashing = { path = "../hashing" }
libc = "0.2.39"
log = "0.4"
nails = "0.5.1"
protobuf = { version = "2.0.6", features = ["with-bytes"] }
sha2 = "0.8"
sharded_lmdb = {  path = "../sharded_lmdb" }
shell-quote = "0.1.0"
store = { path = "../fs/store" }
task_executor = { path = "../task_executor" }
tempfile = "3"
concrete_time = { path = "../concrete_time" }
tokio = { version = "0.2", features = ["process", "rt-threaded", "tcp", "time"] }
tokio-util = { version = "0.2", features = ["codec"] }
uname = "0.1.1"
workunit_store = { path = "../workunit_store" }
regex = "1.3.1"
lazy_static = "1"
parking_lot = "0.6"
itertools = "0.8.0"
serde = "1.0.104"
bincode = "1.2.1"

[dev-dependencies]
maplit = "1.0.1"
mock = { path = "../testutil/mock" }
parking_lot = "0.6"
spectral = "0.6.0"
tempfile = "3"
testutil = { path = "../testutil" }
tokio = { version = "0.2", features = ["macros"] }
