[package]
version = "0.0.1"
edition = "2018"
name = "process_execution"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
async_semaphore = { path = "../async_semaphore" }
bazel_protos = { path = "bazel_protos" }
boxfuture = { path = "../boxfuture" }
bytes = "0.4.5"
derivative = "1.0.2"
digest = "0.8"
fs = { path = "../fs" }
futures = "^0.1.16"
grpcio = { git = "https://github.com/pantsbuild/grpc-rs.git", rev = "4dfafe9355dc996d7d0702e7386a6fedcd9734c0", default_features = false, features = ["protobuf-codec", "secure"] }
hashing = { path = "../hashing" }
log = "0.4"
protobuf = { version = "2.0.6", features = ["with-bytes"] }
sha2 = "0.8"
sharded_lmdb = {  path = "../sharded_lmdb" }
store = { path = "../fs/store" }
task_executor = { path = "../task_executor" }
tempfile = "3"
time = "0.1.40"
tokio-codec = "0.1"
tokio-process = "0.2.1"
tokio-timer = "0.2"
workunit_store = { path = "../workunit_store" }

[dev-dependencies]
maplit = "1.0.1"
mock = { path = "../testutil/mock" }
tempfile = "3"
testutil = { path = "../testutil" }
tokio = "0.1"
