[package]
name = "local_execution_server"
version = "0.1.0"
edition = "2021"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
protos = { path = "../../protos" }
mock = { path = "../mock" }
clap = "4"
structopt = "0.3.26"

