[package]
version = "0.0.1"
edition = "2018"
name = "workunit_store"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
futures = "0.1.27"
parking_lot = "0.6"
rand = "0.6"
time = "0.1.40"
