[package]
version = "0.0.1"
edition = "2018"
name = "workunit_store"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
concrete_time = { path = "../concrete_time" }
hashing = { path = "../hashing" }
hdrhistogram = "7.2"
parking_lot = "0.11"
rand = "0.6"
tokio = { version = "0.2.23", features = ["rt-util"] }
petgraph = "0.4.5"
log = "0.4"
uuid = { version = "0.7", features = ["v4"] }
