[package]
version = "0.0.1"
edition = "2018"
name = "workunit_store"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
concrete_time = { path = "../concrete_time" }
parking_lot = "0.6"
rand = "0.6"
tokio = { version = "0.2", features = ["rt-util"] }
graph = { path = "../graph" }
petgraph = "0.4.5"
