[package]
version = "0.0.1"
edition = "2021"
name = "workunit_store"
authors = ["Pants Build <pantsbuild@gmail.com>"]
publish = false

[dependencies]
bytes = { workspace = true }
concrete_time = { path = "../concrete_time" }
deepsize = { workspace = true }
hashing = { path = "../hashing" }
hdrhistogram = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
petgraph = { workspace = true }
rand = { workspace = true }
smallvec = { version = "1", features = ["union"] }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }

[dev-dependencies]
futures = { workspace = true }
internment = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
