[package]
version = "0.0.1"
edition = "2018"
name = "watch"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
crossbeam-channel = "0.4"
fs = { path = "../fs" }
futures = "0.3"
hashing = { path = "../hashing" }
log = "0.4"
logging = { path = "../logging" }
# TODO: See https://github.com/notify-rs/notify/issues/255.
notify = { git = "https://github.com/pantsbuild/notify", rev = "64880f0662db2b5ecbf25f1cccdca64bb8fac1bc" }
parking_lot = "0.11"
task_executor = { path = "../task_executor" }

[dev-dependencies]
tempfile = "3"
testutil = { path = "../testutil" }
# TODO: See #10291.
tokio = { version = "=0.2.20", features = ["rt-core", "macros"] }
