[package]
version = "0.0.1"
name = "bazel_protos"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[dependencies]
bytes = "0.4.5"
futures = "^0.1.16"
grpcio = { version = "0.2.0", features = ["secure"] }
hashing = { path = "../../hashing" }
protobuf = { version = "1.4.1", features = ["with-bytes"] }

[build-dependencies]
build_utils = { path = "../../build_utils" }
grpcio-compiler = "0.2.0"
protoc-grpcio = "0.1.1"
