[package]
version = "0.0.1"
name = "bazel_protos"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[dependencies]
futures = "0.1.17"
grpcio = { git = "https://github.com/illicitonion/grpc-rs", rev = "eb0ca7eb50a19777e2e1d61b3b734a265d3d64e4", features = ["secure"] }
protobuf = "1.4.1"
