[package]
version = "0.0.1"
edition = "2018"
name = "task_executor"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
logging = { path = "../logging" }
tokio = "0.1"
