[package]
version = "0.0.1"
edition = "2018"
name = "task_executor"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
arc-swap = "1.2"
futures = "0.3"
lazy_static = "1"
logging = { path = "../logging" }
tokio = { version = "0.2.23", features = ["blocking", "rt-threaded"] }
workunit_store = { path = "../workunit_store" }
