[package]
version = "0.0.1"
edition = "2018"
name = "task_executor"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
futures = "0.3"
logging = { path = "../logging" }
num_cpus = "1"
tokio = { version = "0.2", features = ["blocking", "rt-threaded"] }
workunit_store = { path = "../workunit_store" }
