[package]
name = "tar_api"
version = "0.0.1"
edition = "2018"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[lib]
path = "src/tar_api.rs"

[dependencies]
flate2 = "1.0"
tar =  "0.4.20"

[dev-dependencies]
tempfile = "3"
testutil = { path = "../testutil" }
