[package]
version = "0.0.1"
edition = "2021"
name = "protos"
authors = ["Pants Build <pantsbuild@gmail.com>"]
publish = false

[dependencies]
bytes = "1.0"
hashing = { path = "../hashing" }
prost = "0.9"
prost-build = "0.9"
prost-types = "0.9"
tonic = { version = "0.6", features = [
  "transport",
  "codegen",
  "tls",
  "tls-roots",
] }

[build-dependencies]
prost-build = "0.9"
tonic-build = { version = "0.6", features = ["prost"] }
