[package]
version = "0.0.1"
edition = "2018"
authors = ["Pants Build <pantsbuild@gmail.com>"]
name = "concrete_time"
publish = false

[dependencies]
prost = "0.7"
prost-types = "0.7"
serde_derive = "1.0.98"
serde = "1.0.98"
log = "0.4"
