[package]
version = "0.0.1"
edition = "2018"
authors = ["Pants Build <pantsbuild@gmail.com>"]
name = "concrete_time"
publish = false

[dependencies]
protobuf = { version = "2.0.6", features = ["with-bytes"] }
serde_derive = "1.0.98"
serde = "1.0.98"
