[package]
version = "0.0.1"
edition = "2021"
name = "remote_provider_opendal"
authors = ["Pants Build <pantsbuild@gmail.com>"]
publish = false

[dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
grpc_util = { path = "../../grpc_util" }
hashing = { path = "../../hashing" }
http = { workspace = true }
parking_lot = { workspace = true }
prost = { workspace = true }
protos = { path = "../../protos" }
opendal = { workspace = true }
remote_provider_traits = { path = "../remote_provider_traits" }
tokio = { workspace = true }
workunit_store = { path = "../../workunit_store" }

[dev-dependencies]
mock = { path = "../../testutil/mock" }
tempfile = { workspace = true }
testutil = { path = "../../testutil" }
