[package]
version = "0.0.1"
name = "graph"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
boxfuture = { path = "../boxfuture" }
fnv = "1.0.5"
futures = "^0.1.16"
hashing = { path = "../hashing" }
indexmap = "1.0.2"
parking_lot = "0.6"
petgraph = "0.4.5"

[dev-dependencies]
rand = "0.5.3"
