[package]
version = "0.0.1"
edition = "2018"
name = "graph"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
async-trait = "0.1"
fnv = "1.0.5"
futures = "0.3"
log = "0.4"
parking_lot = "0.6"
petgraph = "0.4.5"
tokio = { version = "0.2", features = ["time"] }

[dev-dependencies]
rand = "0.6"
env_logger = "0.5.4"
tokio = { version = "0.2", features = ["macros", "rt-threaded", "time"] }
