[package]
name = "mock"
version = "0.0.1"
edition = "2024"
authors = ["Pants Build <pantsbuild@gmail.com>"]
publish = false

[dependencies]
async-stream = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
hashing = { path = "../../hashing" }
parking_lot = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
protos = { path = "../../protos" }
testutil = { path = ".." }
tokio = { workspace = true, features = ["time"] }
tokio-stream = { workspace = true }
tonic = { workspace = true }

[lints]
workspace = true
