[package]
name = "hashing"
version = "0.0.1"
edition = "2021"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
byteorder = "1.3"
# TODO: Waiting on https://github.com/Aeledfyr/deepsize/pull/30 and https://github.com/Aeledfyr/deepsize/pull/31.
deepsize = { git = "https://github.com/stuhood/deepsize.git", rev = "67c6cfc2afa1303c06b19c1b96ebe11fd3217d34" }
digest = "0.9"
generic-array = "0.14"
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"

[dev-dependencies]
serde_test = "1.0"
