[package]
version = "0.0.1"
edition = "2018"
name = "process_executor"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
clap = "2"
dirs = "1"
env_logger = "0.5.4"
futures = { version = "0.3", features = ["compat"] }
hashing = { path = "../hashing" }
process_execution = { path = "../process_execution" }
store = { path = "../fs/store" }
task_executor = { path = "../task_executor" }
tokio = { version = "0.2", features = ["rt-threaded", "macros"] }
workunit_store = { path = "../workunit_store"}
