[package]
version = "0.0.1"
edition = "2021"
name = "process_executor"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
protos = { path = "../protos" }
clap = "2"
dirs-next = "2"
env_logger = "0.5.4"
fs = { path = "../fs" }
futures = "0.3"
grpc_util = { path = "../grpc_util" }
hashing = { path = "../hashing" }
log = "0.4"
process_execution = { path = "../process_execution" }
prost = "0.9"
shlex = "0.1.1"
store = { path = "../fs/store" }
structopt = "0.3.20"
task_executor = { path = "../task_executor" }
tokio = { version = "1.16", features = ["rt-multi-thread", "macros"] }
workunit_store = { path = "../workunit_store"}
