[package]
version = "0.0.1"
name = "process_executor"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
clap = "2"
env_logger = "0.5.4"
fs = { path = "../fs" }
hashing = { path = "../hashing" }
futures = "^0.1.16"
process_execution = { path = "../process_execution" }
