[package]
version = "0.0.1"
edition = "2021"
name = "process_executor"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
protos = { path = "../protos" }
clap = { version = "3", features = ["derive"] }
dirs-next = "2"
env_logger = "0.10.0"
fs = { path = "../fs" }
futures = "0.3"
grpc_util = { path = "../grpc_util" }
hashing = { path = "../hashing" }
log = "0.4"
process_execution = { path = "../process_execution" }
prost = "0.9"
shlex = "1.1.0"
store = { path = "../fs/store" }
task_executor = { path = "../task_executor" }
tokio = { version = "1.21", features = ["rt-multi-thread", "macros"] }
workunit_store = { path = "../workunit_store"}
remote = { path = "../process_execution/remote"}
