[package]
name = "local_cas"
version = "0.0.1"
edition = "2021"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
mock = { path = "../mock" }
clap = "3"
env_logger = "0.10.0"

