[package]
name = "local_cas"
version = "0.0.1"
edition = "2021"
authors = ["Pants Build <pantsbuild@gmail.com>"]
publish = false

[dependencies]
mock = { path = "../mock" }
clap = { workspace = true }
env_logger = { workspace = true }
