[package]
version = "0.0.1"
edition = "2021"
name = "testutil"
authors = ["Pants Build <pantsbuild@gmail.com>"]
publish = false

[dependencies]
async-stream = { workspace = true }
bytes = { workspace = true }
fs = { path = "../fs" }
grpc_util = { path = "../grpc_util" }
hashing = { path = "../hashing" }
prost = { workspace = true }
protos = { path = "../protos" }
tempfile = { workspace = true }
tokio = { workspace = true }
