[package]
version = "0.0.1"
edition = "2018"
name = "testutil"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
async-stream = "0.2"
bazel_protos = { path = "../process_execution/bazel_protos" }
bytes = "0.5"
grpc_util = { path = "../grpc_util" }
fs = { path = "../fs" }
hashing = { path = "../hashing" }
prost = "0.6"
protobuf = { version = "2.0.6", features = ["with-bytes"] }
