[package]
version = "0.0.1"
edition = "2021"
name = "docker"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
async-stream = "0.3"
async-trait = "0.1"
async-lock = "2.5"
bollard = { git = "https://github.com/fussybeaver/bollard.git", rev = "2d66d11b44aeff0373ece3d64a44b243e5152973" }
bollard-stubs = { git = "https://github.com/fussybeaver/bollard.git", rev = "2d66d11b44aeff0373ece3d64a44b243e5152973" }
fs = { path = "../../fs" }
futures = "0.3"
log = "0.4"
nails = "0.13"
store = { path = "../../fs/store" }
task_executor = { path = "../../task_executor" }
tokio = { version = "1.21", features = ["net", "process", "rt-multi-thread", "sync", "time"] }
tokio-rustls = "0.23"
tokio-util = { version = "0.7", features = ["codec"] }
workunit_store = { path = "../../workunit_store" }
parking_lot = "0.12"
async-oncecell = "0.2"
once_cell = "1.15"
process_execution = { path = ".." }
hashing = { path = "../../hashing" }
bytes = "1.2"

[dev-dependencies]
env_logger = "0.10.0"
maplit = "1.0.1"
mock = { path = "../../testutil/mock" }
parking_lot = "0.12"
sharded_lmdb = { path = "../../sharded_lmdb" }
spectral = "0.6.0"
tempfile = "3"
testutil = { path = "../../testutil" }
tokio = { version = "1.21", features = ["macros"] }
