[package]
name = "fs_util"
version = "0.0.1"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[dependencies]
bazel_protos = { path = "../../process_execution/bazel_protos" }
boxfuture = { path = "../../boxfuture" }
clap = "2"
fs = { path = ".." }
futures = "0.1.16"
hashing = { path = "../../hashing" }
protobuf = "1.4.1"
