[package]
name = "fs_util"
version = "0.0.1"
edition = "2018"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
bazel_protos = { path = "../../process_execution/bazel_protos" }
boxfuture = { path = "../../boxfuture" }
bytes = "0.5"
clap = "2"
env_logger = "0.5.4"
fs = { path = ".." }
futures01 = { package = "futures", version = "0.1" }
futures = { version = "0.3", features = ["compat"] }
hashing = { path = "../../hashing" }
parking_lot = "0.11"
prost = { git = "https://github.com/danburkert/prost", rev = "a1cccbcee343e2c444e1cd2738c7fba2599fc391" }
rand = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
store = { path = "../store" }
task_executor = { path = "../../task_executor" }
tokio = { version = "0.2.23", features = ["rt-threaded", "macros"] }
workunit_store = { path = "../../workunit_store" }
