[package]
name = "fs_util"
version = "0.0.1"
edition = "2018"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
boxfuture = { path = "../../boxfuture" }
bytes = "0.4.5"
clap = "2"
env_logger = "0.5.4"
fs = { path = ".." }
futures01 = { package = "futures", version = "0.1" }
hashing = { path = "../../hashing" }
parking_lot = "0.6"
protobuf = { version = "2.0.6", features = ["with-bytes"] }
rand = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
store = { path = "../store" }
task_executor = { path = "../../task_executor" }
tokio = "0.1"
workunit_store = { path = "../../workunit_store" }
