[package]
name = "fs_util"
version = "0.0.1"
edition = "2021"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]
publish = false

[dependencies]
protos = { path = "../../protos" }
bytes = "1.2"
clap = "3"
env_logger = "0.10.0"
grpc_util = { path = "../../grpc_util" }
fs = { path = ".." }
futures = "0.3"
hashing = { path = "../../hashing" }
log = "0.4"
parking_lot = "0.12"
prost = "0.9"
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
store = { path = "../store" }
task_executor = { path = "../../task_executor" }
tokio = { version = "1.21", features = ["rt-multi-thread", "macros"] }
workunit_store = { path = "../../workunit_store" }
