[package]
name = "fs_util"
version = "0.0.1"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[dependencies]
bazel_protos = { path = "../../process_execution/bazel_protos" }
boxfuture = { path = "../../boxfuture" }
bytes = "0.4.5"
clap = "2"
env_logger = "0.5.4"
fs = { path = ".." }
futures = "0.1.21"
hashing = { path = "../../hashing" }
protobuf = { version = "1.4.1", features = ["with-bytes"] }
